spring.application.name=demo

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# SERVER
# ===============================
server.port=8080

jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=86400000

# ===============================
# VNPAY CONFIG
# ===============================
# ?i?n thông tin sandbox th?t c?a m ? ?ây
vnpay.tmn-code=MS1G6QAO
vnpay.hash-secret=WC99XI17H1SYCM2KMNVXFUI80JEUSY3J

# URL thanh toán sandbox VNPAY
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# URL backend public ?? VNPAY tr? ng??i dùng v? sau thanh toán
# N?u test local thì expose backend b?ng ngrok r?i thay domain vào ?ây
# Ví d?: https://abc123.ngrok-free.app/api/public/payments/vnpay/return
vnpay.return-url=http://localhost:8080/api/public/payments/vnpay/return

# URL frontend ?? backend redirect v? trang k?t qu? bên bán online
app.frontend-base-url=http://localhost:5173